image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-browser

tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

tasks:
  - before: npm i -g firebase-tools